[build]
  base = "todoApp"
  command = "echo 'FastAPI backend - not suitable for static deployment'"
  publish = "todoApp"

[build.environment]
  PYTHON_VERSION = "3.12"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  command = "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
  port = 8000
  publish = "todoApp"
